name: Lint

on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        
      - name: Set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install black
          
      - name: Run Pylint
        run: |
          black .
          
      - name : Commit Data
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Auto-lint code"
          git push
        
      
